// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOX7wHd6R6F75V7VmarDbRU9wT7FJhoYI',
    appId: '1:1048336464033:web:58315850d4b25dc9b298e0',
    messagingSenderId: '1048336464033',
    projectId: 'enableu-e9872',
    authDomain: 'enableu-e9872.firebaseapp.com',
    storageBucket: 'enableu-e9872.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAsDoeK90d5NHrwBfntrnhUtjpfBzgtpI',
    appId: '1:1048336464033:android:b575010ed302ccd0b298e0',
    messagingSenderId: '1048336464033',
    projectId: 'enableu-e9872',
    storageBucket: 'enableu-e9872.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyY6UbuT9MTgmrBCCp-uQ5bh5_ZOeEZ3A',
    appId: '1:1048336464033:ios:d26e13e7faa8f46fb298e0',
    messagingSenderId: '1048336464033',
    projectId: 'enableu-e9872',
    storageBucket: 'enableu-e9872.appspot.com',
    iosBundleId: 'com.example.fyp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyY6UbuT9MTgmrBCCp-uQ5bh5_ZOeEZ3A',
    appId: '1:1048336464033:ios:60e94be74f87722eb298e0',
    messagingSenderId: '1048336464033',
    projectId: 'enableu-e9872',
    storageBucket: 'enableu-e9872.appspot.com',
    iosBundleId: 'com.example.fyp.RunnerTests',
  );
}
